<?xml version="1.0"?>
<package format="3">
  <name>dogvision_bringup</name>
  <version>1.0.0</version>
  <description>ROS 2 launch files and configuration for the dogvision workspace</description>
  <maintainer email="toe@todo.todo">toe</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>dogvision_arm</exec_depend>
  <exec_depend>dogvision_vision</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
