<?xml version="1.0"?>
<package format="2">
  <name>dogvision_bringup</name>
  <version>1.0.0</version>
  <description>Launch files and configuration for dogvision26 project</description>

  <maintainer email="toe@todo.todo">toe</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend>dogvision_arm</exec_depend>
  <exec_depend>dogvision_camera</exec_depend>
  <exec_depend>dogvision_vision</exec_depend>
</package>
