<?xml version="1.0"?>
<package format="3">
  <name>dogvision_arm</name>
  <version>1.0.0</version>
  <description>ROS 2 arm serial communication and mission nodes</description>
  <maintainer email="toe@todo.todo">toe</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
