arm_mission_node:
  ros__parameters:
    start_pos:
      LF: {x: 160.0, y: 220.0}
      RF: {x: 160.0, y: -220.0}
      LB: {x: -160.0, y: 220.0}
      RB: {x: -160.0, y: -220.0}
    stow_pos:
      LF: {x: 220.0, y: 380.0}
      RF: {x: 220.0, y: -380.0}
      LB: {x: -220.0, y: 380.0}
      RB: {x: -220.0, y: -380.0}
    pick_pos:
      LF: {x: 450.0, y: 450.0}
      RF: {x: 450.0, y: -450.0}
      LB: {x: -450.0, y: 450.0}
      RB: {x: -450.0, y: -450.0}
    place_pos:
      LF: {x: 90.0, y: 900.0}
      RF: {x: 90.0, y: -900.0}
      LB: {x: -90.0, y: 900.0}
      RB: {x: -90.0, y: -900.0}
